
version: 2

models:
    - name: bank_transfer_payments
      description: "Payments table filtered on bank_transfer"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

          - name: order_id
            description: "The order id. The same order can have different payment methods"
            tests:
                - not_null

          - name: payment_method
            description: "Method used to pay"
            tests:
                - not_null

          - name: amount
            description: "Order amount"
            tests:
                - not_null

sources:
  - name: dbt_testing
    tables:
      - name: raw_payments
