name: dbt-oracle Testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: silverax/dbt-oracle-adapter:oracle-18.4.0-xe

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
  
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run dbtspec tests
      run: |
        python -m pip install pytest
        pytest ../specs/oracle.dbtspec
